In [1]:
# 2 linear_model.LogisticRegression

In [1]:
'''class sklearn.linear_model.LogisticRegression (penalty=’l2’, dual=False, tol=0.0001, C=1.0,
fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100,
multi_class=’warn’, verbose=0, warm_start=False, n_jobs=None)'''

'class sklearn.linear_model.LogisticRegression (penalty=’l2’, dual=False, tol=0.0001, C=1.0,\nfit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver=’warn’, max_iter=100,\nmulti_class=’warn’, verbose=0, warm_start=False, n_jobs=None)'

In [ ]:
# 2.2 重要参数penalty & C

In [ ]:
# 2.2.1 正则化

In [2]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.datasets import load_breast_cancer
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
data = load_breast_cancer()
X = data.data
y = data.target

In [4]:
data.data.shape

(569, 30)

In [5]:
lrl1 = LR(penalty="l1",solver="liblinear",C=0.5,max_iter=1000)

In [6]:
lrl2 = LR(penalty="l2",solver="liblinear",C=0.5,max_iter=1000) 

In [7]:
#逻辑回归的重要属性coef_，查看每个特征所对应的参数
lrl1 = lrl1.fit(X,y)

In [8]:
lrl1.coef_

array([[ 4.00097731,  0.03192668, -0.13715571, -0.01622409,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.50485668,  0.        , -0.07128422,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.2458637 , -0.12855377, -0.01441098,  0.        ,
         0.        , -2.04115668,  0.        ,  0.        ,  0.        ]])

In [9]:
(lrl1.coef_ != 0).sum(axis=1)#不为0的特征个数

array([10])

In [10]:
lrl2 = lrl2.fit(X,y)
lrl2.coef_

array([[ 1.61543234e+00,  1.02284415e-01,  4.78483684e-02,
        -4.43927107e-03, -9.42247882e-02, -3.01420673e-01,
        -4.56065677e-01, -2.22346063e-01, -1.35660484e-01,
        -1.93917198e-02,  1.61646580e-02,  8.84531037e-01,
         1.20301273e-01, -9.47422278e-02, -9.81687769e-03,
        -2.37399092e-02, -5.71846204e-02, -2.70190106e-02,
        -2.77563737e-02,  1.98122260e-04,  1.26394730e+00,
        -3.01762592e-01, -1.72784162e-01, -2.21786411e-02,
        -1.73339657e-01, -8.79070550e-01, -1.16325561e+00,
        -4.27661014e-01, -4.20612369e-01, -8.69820058e-02]])